name: Gdrive-file-to-link

on:
  workflow_dispatch:
    inputs:
      FILE_LINK:
        description: 'file link'
        required: true
        default: 'https://drive.google.com/file/d/1FpKs2CQEM0FOLgBhfobEEDzo-FYX_7_3/view?usp=sharing'

jobs:
  build:
    name: Gdrive downloader by ${{ github.actor }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Getting tools ready 
      run: |
        pip install gdown 
        python3 convertor.py ${{ github.event.inputs.FILE_LINK }} > link.txt
        echo "FILE_ID=$(<link.txt)" >> $GITHUB_ENV
    
    - name: Downloading file from Gdrive
      run: |
        mkdir Gdrive && cd Gdrive
        gdown https://drive.google.com/uc?id=${{ env.FILE_ID }}
        for filename in $(ls)
        do
        echo "FILE_NAME=$filename" >> $GITHUB_ENV
        done;
    - name: Check file size
      run: |
        if [[ $(stat -c '%s' *.*) -gt 2147483648 ]]; then
        echo "The File is larger than 2GB"
        cd Exit
        else
        echo "File is smaller than or equal to 2GB"
        fi
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Upload to Github
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Gdrive/*.*
        name: ${{ env.FILE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
